[package]
name = "first_step_rust"
version = "0.1.0"
authors = ["MaxXSoft <x@MaxXSoft.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.8", features = ["macros"] }
